name: Update SDK Redis Keys

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Deployment target'
        required: true
        default: 'dev'
        options:
          - dev
          - stage
          - prod

jobs:
  update-redis-keys:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      id-token: write

    steps:
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          project_id: "x-cycling-414419"
          workload_identity_provider: "projects/577495761779/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider"
          service_account: "service-account-github-act-764@x-cycling-414419.iam.gserviceaccount.com"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: "gke-gcloud-auth-plugin,beta"

      - name: Verify gcloud authentication
        run: |
          gcloud auth list

      - name: Set up SSH SOCKS proxy
        env:
          REDIS_HOST: "${{ github.event.inputs.target == 'stage' && '10.128.0.62' || github.event.inputs.target == 'prod' && '10.128.15.192' || '10.128.0.114' }}"
          PROXY_CLUSTER: "${{ github.event.inputs.target == 'stage' && 'proxy-stage-cluster' || github.event.inputs.target == 'prod' && 'proxy-prod-cluster' || 'proxy-dev-cluster' }}"
        run: |
          gcloud beta compute ssh $PROXY_CLUSTER \
            --project x-cycling-414419 \
            --zone us-central1-a \
            --tunnel-through-iap \
            --ssh-flag="-4 -L 6379:$REDIS_HOST:6379 -N -q -f"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Redis
        run: npm install ioredis && node .github/workflows/createSdkSource.js
